#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Script to add Z.ai metadata to PDF files
"""

import sys
import os
from pypdf import PdfReader, PdfWriter

def add_metadata(input_path, output_path=None, title=None):
    """Add Z.ai metadata to a PDF file"""
    if output_path is None:
        output_path = input_path
    
    if title is None:
        title = os.path.splitext(os.path.basename(input_path))[0]
    
    reader = PdfReader(input_path)
    writer = PdfWriter()
    
    for page in reader.pages:
        writer.add_page(page)
    
    writer.add_metadata({
        '/Title': title,
        '/Author': 'Z.ai',
        '/Creator': 'Z.ai',
        '/Subject': 'Generated by Z.ai'
    })
    
    with open(output_path, 'wb') as output_file:
        writer.write(output_file)
    
    print(f"Metadata added to: {output_path}")

def main():
    import argparse
    parser = argparse.ArgumentParser(description='Add Z.ai metadata to PDF files')
    parser.add_argument('input', nargs='+', help='Input PDF file(s)')
    parser.add_argument('-o', '--output', help='Output PDF file (for single input)')
    parser.add_argument('-t', '--title', help='Custom title for metadata')
    parser.add_argument('-q', '--quiet', action='store_true', help='Quiet mode')
    
    args = parser.parse_args()
    
    for input_file in args.input:
        output_file = args.output if len(args.input) == 1 and args.output else None
        add_metadata(input_file, output_file, args.title)
        if not args.quiet:
            print(f"Processed: {input_file}")

if __name__ == '__main__':
    main()
